//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon_Shuffle_Unpacker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pokemon_Shuffle_Unpacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0A040000	Item Graphics
        ///1F900000	Match_Mega Graphics
        ///21040000	Item Select GMBs
        ///26740000	Puzzle GMBs
        ///2D700000	Special Enemy Graphics
        ///4E540000	Streetpass GMB and Present Table
        ///58F80000	Debug Menu
        ///66140000	Savefile (My Data) GMB
        ///69680000	Layout Archives
        ///72940000	Support Menu GMB
        ///8A640000	Serial Code GMB
        ///8BA80000	Stage Result GMBs
        ///8F280000	AppCore and Misc GMBs
        ///91280000	128x128 Pokemon Graphics
        ///9D3C0000	Options GMB
        ///9EB40000	Type PTCLs
        ///A4700000	Stage Select GMB
        ///A6540000	Pokemon Catching UI
        ///A8A40 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Archive_Names {
            get {
                return ResourceManager.GetString("Archive_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEEFBC3E	animData.bin
        ///705847E4	appcore.gmb
        ///50CA4D34	appear_legend.bch
        ///ABE67DDC	appear_normal.bch
        ///AEF78148	appear_visionary.bch
        ///64E68048	areaData.bin
        ///E3C81994	attack_enemy.bch
        ///0C3875BE	AttributePlate.arc
        ///EBCF39AA	back_boss.bch
        ///E3C9EB7E	back_legend.bch
        ///72D79B32	back_visionary.bch
        ///F8436378	BigPinkButton.arc
        ///D9DDBBAE	black_puzzle.bch
        ///3B0B9A06	bossAction.bin
        ///EF142422	bossActionPokemonData.bin
        ///1F41D9F4	BossHpGauge.arc
        ///B80F26A0	BossName.arc
        ///BC696976	BossTurn.arc
        ///CC1191AA	camera_catch_l.bch
        ///C3A41 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_Names {
            get {
                return ResourceManager.GetString("File_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F054000A	JP
        ///F0540012	US
        ///F0540022	UK
        ///F0540042	FR
        ///F0540082	GE
        ///F0540102	IT
        ///F0540202	SP
        ///F0550002	NAFR
        ///F0560002	NASP.
        /// </summary>
        internal static string Message_Regions {
            get {
                return ResourceManager.GetString("Message_Regions", resourceCulture);
            }
        }
    }
}
